name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: List directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "cmd directory contents:"
          ls -la cmd || echo "cmd directory not found"
          echo "Finding main.go files:"
          find . -name "main.go" || echo "No main.go files found"
          echo "Repository structure:"
          find . -type d | sort || echo "Failed to list directories"

      - name: Check main.go exists
        run: |
          if [ ! -f "cmd/watchs/main.go" ]; then
            echo "Error: cmd/watchs/main.go file not found. Please ensure this file is committed to the repository."
            exit 1
          fi
          
          echo "Content of main.go:"
          cat cmd/watchs/main.go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 